meta_product_name: "NextCity"
meta_title: "NextCity - Trouvez la ville qui vous correspond le mieux."
meta_description: "Description"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards